In [7]:
#load libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [8]:
#load data
df = pd.read_csv("../data/machine_learning_dataset.csv")

df.head()

,SampleID,Collinsella,Blautia,Romboutsia,Clostridium sensu stricto 1,Catenibacterium,Bifidobacterium,Dorea,Holdemanella,Erysipelotrichaceae UCG-003,...,Helicobacter,Sanguibacteroides,W5053,Anaerospora,Cardiobacterium,Agrilactobacillus,Paracoccus,Dolosigranulum,Coprobacter,Disease
0,SRR11127890,0.029102,0.264698,0.087453,0.045392,0.000000,0.033177,0.016134,0.021806,0.117977,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Healthy
1,SRR11127891,0.017497,0.081164,0.101884,0.292659,0.002252,0.000000,0.029101,0.053934,0.026458,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Healthy
2,SRR11127892,0.169139,0.162532,0.037848,0.080000,0.023203,0.000000,0.056663,0.000000,0.013733,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Healthy
3,SRR11127894,0.150082,0.128379,0.012224,0.002288,0.137084,0.000000,0.028339,0.081061,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Healthy
4,SRR11127895,0.049909,0.090510,0.126907,0.189442,0.000238,0.001309,0.027248,0.166940,0.059401,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Healthy

In [9]:
#inspect data
print(df.shape)

df.info()

df.describe()

(131, 318)
<class 'pandas.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Columns: 318 entries, SampleID to Disease
dtypes: float64(316), str(2)
memory usage: 325.6 KB

,Collinsella,Blautia,Romboutsia,Clostridium sensu stricto 1,Catenibacterium,Bifidobacterium,Dorea,Holdemanella,Erysipelotrichaceae UCG-003,Subdoligranulum,...,Nocardiopsis,Helicobacter,Sanguibacteroides,W5053,Anaerospora,Cardiobacterium,Agrilactobacillus,Paracoccus,Dolosigranulum,Coprobacter
count,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,...,1.310000e+02,1.310000e+02,1.310000e+02,1.310000e+02,1.310000e+02,1.310000e+02,1.310000e+02,1.310000e+02,1.310000e+02,1.310000e+02
mean,0.076086,0.154536,0.063892,0.090024,0.042519,0.045273,0.035685,0.039752,0.023133,0.031581,...,1.319811e-07,1.369683e-07,1.963523e-07,1.459298e-07,1.436654e-07,1.369794e-07,1.698807e-07,1.550833e-07,2.065141e-07,8.944865e-07
std,0.056955,0.080485,0.063857,0.097556,0.061860,0.076613,0.022143,0.049292,0.033356,0.032431,...,1.510593e-06,1.567674e-06,2.247355e-06,1.670243e-06,1.644325e-06,1.567801e-06,1.944373e-06,1.775010e-06,2.363662e-06,6.646442e-06
min,0.000000,0.002932,0.000000,0.000254,0.000000,0.000000,0.000402,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.032610,0.091372,0.009489,0.015854,0.000282,0.000061,0.019282,0.000171,0.001242,0.008077,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,0.065586,0.141201,0.044065,0.064057,0.013375,0.003259,0.031716,0.024364,0.009479,0.022209,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,0.105467,0.206667,0.099387,0.134544,0.059185,0.063670,0.047321,0.062462,0.027370,0.047599,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,0.298546,0.367091,0.262366,0.615693,0.295283,0.369357,0.114069,0.261768,0.169548,0.181817,...,1.728952e-05,1.794285e-05,2.572215e-05,1.911680e-05,1.882016e-05,1.794430e-05,2.225437e-05,2.031591e-05,2.705335e-05,6.767731e-05

In [10]:
#check missing values
df.isnull().sum().sort_values(ascending=False).head(20)

SampleID                        0
Collinsella                     0
Blautia                         0
Romboutsia                      0
Clostridium sensu stricto 1     0
Catenibacterium                 0
Bifidobacterium                 0
Dorea                           0
Holdemanella                    0
Erysipelotrichaceae UCG-003     0
Subdoligranulum                 0
[Ruminococcus] torques group    0
Ruminococcus                    0
[Eubacterium] hallii group      0
Turicibacter                    0
Streptococcus                   0
Terrisporobacter                0
Senegalimassilia                0
Enterococcus                    0
Anaerostipes                    0
dtype: int64

In [6]:
df.isnull().sum().sum()

np.int64(0)

In [12]:
#check duplicated
df["SampleID"].duplicated().sum()

df["SampleID"].nunique()

131

In [13]:
#outcome variables
df["Disease"].value_counts()
df["Disease"].value_counts(normalize=True) * 100

Disease
Type 2 diabetes    50.381679
Healthy            49.618321
Name: proportion, dtype: float64

In [18]:
#separate feature and labels
X = df.drop(columns = ["SampleID", "Disease"])
y = df["Disease"]

X.dtypes.value_counts()

float64    316
Name: count, dtype: int64

In [19]:
#remove zero variance features
from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(threshold=0)

X = pd.DataFrame(
    selector.fit_transform(X),
    columns=X.columns[selector.get_support()]
)

print(X.shape)

(131, 316)

In [20]:
#remove near-zero prevalence genra
prevalence = (X > 0).sum(axis=0)

keep = prevalence >= 0.10 * len(X)

X = X.loc[:, keep]

print(X.shape)

(131, 142)

In [21]:
#train test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [22]:
#save processed data 
train = X_train.copy()
train["Disease"] = y_train.values

test = X_test.copy()
test["Disease"] = y_test.values

train.to_csv("../data/train.csv", index=False)
test.to_csv("../data/test.csv", index=False)

In [24]:
X_filtered = X.copy()
X_filtered["Disease"] = y.values

# Include SampleID again
X_filtered.insert(0, "SampleID", df["SampleID"])

X_filtered.to_csv(
    "../data/machine_learning_dataset_filtered.csv",
    index=False
)

print(X_filtered.shape)

(131, 144)